import React, { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type LanguageCode = 'en' | 'hi' | 'ta' | 'kn' | 'bh';

type TranslationDict = Record<string, string>;

const STORAGE_KEY = '@MediVault:language';

const resources: Record<LanguageCode, TranslationDict> = {
  en: {
    'common.patient': 'Patient',
    'common.doctor': 'Doctor',
    'common.cancel': 'Cancel',
    'common.continue': 'Continue',
    'common.language': 'Language',
    'common.user': 'User',
    'common.loading': 'Loading...',
    'common.viewAll': 'View All',
    'common.view': 'View',
    'common.add': '+ Add',
    'common.retry': 'Retry',
    'common.error': 'Error',

    'msg.title': 'Messages',
    'msg.subtitle': 'Patient communications',
    'msg.noMessagesYet': 'No messages yet',
    'msg.searchPlaceholder': 'Search patients...',
    'msg.chat': 'Chat',
    'msg.typeMessage': 'Type a message...',

    'notif.title': 'Notifications',
    'notif.markAll': 'Mark all',
    'notif.unread': 'unread',
    'notif.allCaughtUp': 'All caught up!',
    'notif.noneHere': 'No notifications here.',
    'notif.loading': 'Loading notifications...',
    'notif.doctorTitle': 'Doctor Notifications',
    'notif.patientTitle': 'Patient Notifications',
    'notif.doctorSub': 'Patient alerts and system updates',
    'notif.patientSub': 'Medications, messages and updates',
    'notif.filter.all': 'All',
    'notif.filter.unread': 'Unread',
    'notif.filter.critical': 'Critical',
    'notif.filter.report': 'Report',
    'notif.filter.medicine': 'Medicine',
    'notif.filter.message': 'Message',
    'notif.error.loadFailed': 'Failed to load notifications',
    'notif.error.markOne': 'Failed to mark as read',
    'notif.error.markAll': 'Failed to mark all as read',

    'patients.title': 'Patients',
    'patients.totalPatients': 'total patients',
    'patients.loading': 'Loading patients...',
    'patients.critical': 'Critical',
    'patients.monitor': 'Under Monitor',
    'patients.stable': 'Stable',
    'patients.searchPlaceholder': 'Search by name, condition...',
    'patients.showing': 'Showing',
    'patients.of': 'of',
    'patients.blood': 'Blood',
    'patients.allergies': 'allergies',
    'patients.viewDetails': 'View Details',
    'patients.noPatients': 'No patients found',
    'patients.tryAnotherSearch': 'Try a different search term',

    'alerts.title': 'Alerts',
    'alerts.subtitle': 'Action required',
    'alerts.totalAlerts': 'Total Alerts',
    'alerts.pending': 'Pending',
    'alerts.responded': 'Responded',
    'alerts.loading': 'Loading alerts...',
    'alerts.pendingAction': 'Pending Alerts - Action Required',
    'alerts.recommended': 'Recommended',
    'alerts.viewPatient': 'View Patient',
    'alerts.sendSms': 'Send SMS',
    'alerts.markResponded': 'Mark Responded',
    'alerts.dismiss': 'Dismiss',
    'alerts.allCaughtUp': 'All Caught Up!',
    'alerts.noPending': 'No pending alerts right now.',
    'alerts.sendSmsViaTwilio': 'Send SMS via Twilio',
    'alerts.to': 'To',
    'alerts.message': 'Message',
    'alerts.typeMessage': 'Type your message...',
    'alerts.sendViaTwilio': 'Send via Twilio',
    'alerts.smsSentTitle': 'SMS Sent',
    'alerts.messageSentTo': 'Message sent to',
    'alerts.viaTwilio': 'via Twilio.',
    'alerts.loadFailed': 'Failed to load alerts',
    'alerts.unknown': 'Unknown',

    'med.title': 'Medicines',
    'med.subtitle': 'Track your medications',
    'med.alert.requiredTitle': 'Required',
    'med.alert.enterMedicineName': 'Please enter medicine name',
    'med.alert.enterDosage': 'Please enter dosage',
    'med.alert.successTitle': 'Success',
    'med.alert.added': 'Medicine added successfully',
    'med.alert.errorTitle': 'Error',
    'med.error.fetchFailed': 'Failed to fetch medicines',
    'med.error.addFailed': 'Failed to add medicine',
    'med.error.markDoseFailed': 'Failed to mark dose',
    'med.stats.active': 'Active Medicines',
    'med.stats.takenToday': 'Taken Today',
    'med.stats.pending': 'Pending',
    'med.stats.avgAdherence': 'Avg Adherence',
    'med.section.todaySchedule': "Today's Schedule",
    'med.section.weeklyAdherence': 'Weekly Adherence',
    'med.section.myMeds': 'My Medicines',
    'med.empty.noScheduled': 'No medications scheduled',
    'med.empty.noMeds': 'No medicines added yet',
    'med.badge.taken': 'Taken',
    'med.action.take': 'Take',
    'med.action.retake': 'Retake',
    'med.action.addMedicine': 'Add Medicine',
    'med.avg': 'avg',
    'med.noSchedule': 'No schedule',
    'med.started': 'Started',
    'med.modal.addNew': 'Add New Medicine',
    'med.field.name': 'Medicine Name',
    'med.field.dosage': 'Dosage',
    'med.field.frequency': 'Frequency',
    'med.field.timeSlots': 'Time Slots',
    'med.field.instructions': 'Instructions (optional)',
    'med.placeholder.name': 'e.g. Paracetamol',
    'med.placeholder.dosage': 'e.g. 500mg',
    'med.placeholder.time': 'HH:MM',
    'med.placeholder.instructions': 'e.g. Take after food',

    'reports.title': 'Reports',
    'reports.subtitle': 'Upload and manage your reports',
    'reports.section.upload': 'Upload Medical Report',
    'reports.section.myReports': 'My Reports',
    'reports.field.reportType': 'Report Type',
    'reports.fileSelected': 'File Selected',
    'reports.defaultImageName': 'image.jpg',
    'reports.tapToUpload': 'Tap to upload file',
    'reports.supportedFormats': 'PDF, JPG, PNG up to 10MB',
    'reports.uploadingAnalysing': 'Uploading and Analysing...',
    'reports.action.uploadReport': 'Upload Report',
    'reports.action.remove': 'Remove',
    'reports.action.delete': 'Delete',
    'reports.aiAnalyzing': 'AI is analysing your report...',
    'reports.uploadSuccessTitle': 'Upload Successful!',
    'reports.disclaimer': 'Not a substitute for professional medical advice.',
    'reports.reportsCount': 'reports',
    'reports.empty.noReports': 'No reports uploaded yet',
    'reports.empty.uploadFirst': 'Upload your first medical report above',
    'reports.aiSummary': 'AI SUMMARY',
    'reports.alert.permissionTitle': 'Permission Required',
    'reports.alert.permissionBody': 'Please allow access to your photos to upload reports.',
    'reports.alert.selectFileTitle': 'Select File',
    'reports.alert.selectFileBody': 'Please select a file to upload',
    'reports.alert.uploadedSuccessfully': 'Report uploaded successfully.',
    'reports.alert.uploadFailedTitle': 'Upload Failed',
    'reports.alert.deleteTitle': 'Delete Report',
    'reports.alert.deleteBody': 'Are you sure you want to delete this report?',
    'reports.alert.deleted': 'Report deleted',
    'reports.error.pickImage': 'Failed to pick image',
    'reports.error.uploadFailed': 'Failed to upload report',
    'reports.error.openFailed': 'Failed to open report',
    'reports.error.deleteFailed': 'Failed to delete report',

    'symptoms.title': 'Symptom Checker',
    'symptoms.subtitle': 'AI-powered triage assistant',
    'symptoms.section.describe': 'Describe Your Symptoms',
    'symptoms.section.matchedDoctors': 'Matched Doctors',
    'symptoms.section.recentChecks': 'Recent Checks',
    'symptoms.whatExperiencing': 'What symptoms are you experiencing?',
    'symptoms.placeholder': 'e.g. I have high fever since yesterday, severe headache, body ache...',
    'symptoms.quickSelect': 'Quick Select Common Symptoms',
    'symptoms.analyzing': 'Analysing with AI...',
    'symptoms.analyzeButton': 'Analyse Symptoms',
    'symptoms.processing': 'AI is processing your symptoms...',
    'symptoms.disclaimer': 'AI Disclaimer: For informational purposes only. Not a substitute for professional medical diagnosis.',
    'symptoms.alert.analysisComplete': 'Analysis Complete',
    'symptoms.error.analyzeFailed': 'Failed to analyze symptoms',
    'symptoms.urgency': 'Urgency',
    'symptoms.recommended': 'Recommended',
    'symptoms.yourSymptoms': 'YOUR SYMPTOMS',
    'symptoms.aiAdvice': 'AI ADVICE',
    'symptoms.possibleConditions': 'POSSIBLE CONDITIONS',
    'symptoms.available': 'Available',
    'symptoms.busy': 'Busy',
    'symptoms.book': 'Book',
    'symptoms.full': 'Full',
    'symptoms.empty.noHistory': 'No symptom history yet',
    'symptoms.analyzed': 'Analyzed',

    'timeline.title': 'Health Timeline',
    'timeline.subtitle': 'Your complete health story',
    'timeline.allEvents': 'All Events',
    'timeline.empty.noEvents': 'No events in this category',
    'timeline.empty.eventsAppear': 'Your health events will appear here',
    'timeline.error.loadFailed': 'Failed to load timeline',

    'records.title': 'Medical Records',
    'records.subtitle': 'Complete health history',
    'records.loading': 'Loading records...',
    'records.na': 'N/A',
    'records.stats.total': 'Total Records',
    'records.stats.admissions': 'Admissions',
    'records.stats.opd': 'OPD Visits',
    'records.stats.checkups': 'Check-ups',
    'records.empty.none': 'No records found',
    'records.empty.appear': 'Your medical records will appear here',
    'records.section.doctorNotes': "DOCTOR'S NOTES",
    'records.section.prescribed': 'PRESCRIBED MEDICINES',
    'records.section.files': 'ATTACHED FILES',
    'records.openingFile': 'Opening file',
    'records.modal.addTitle': 'Add Medical Record',
    'records.field.visitType': 'Visit Type',
    'records.placeholder.notes': 'Notes, instructions, observations...',
    'records.action.saveRecord': 'Save Record',
    'records.error.loadFailed': 'Failed to load records',
    'records.error.createFailed': 'Failed to create record',

    'qr.title': 'Emergency QR Profile',
    'qr.subtitle': 'Your emergency health card',
    'qr.section.code': 'Your Emergency QR Code',
    'qr.section.emergencyInfo': 'Emergency Information',
    'qr.section.currentMeds': 'Current Medications',
    'qr.section.updateInfo': 'Update Emergency Information',
    'qr.warningPrefix': 'This QR code can be scanned by emergency responders or doctors',
    'qr.warningBold': 'without requiring a login',
    'qr.warningSuffix': 'Keep it accessible',
    'qr.download': 'Download',
    'qr.copyLink': 'Copy Link',
    'qr.copied': 'Copied',
    'qr.savedToGallery': 'QR saved to gallery.',
    'qr.linkCopied': 'Link copied to clipboard.',
    'qr.noLoginRequired': 'No login required',
    'qr.viewMedsInRecords': 'View medications in the Records section',
    'qr.saveProfile': 'Save Emergency Profile',
    'qr.profileUpdated': 'Emergency profile updated.',
    'qr.unknown': 'Unknown',
    'qr.none': 'None',
    'qr.notSet': 'Not set',
    'qr.condition': 'Condition',
    'qr.bloodType': 'Blood Type',
    'qr.emergencyContact': 'Emergency Contact',
    'qr.error.loadFailed': 'Failed to load QR profile',

    'patientDetails.title': 'Patient Details',
    'patientDetails.loadingPatient': 'Loading patient...',
    'patientDetails.unknownPatient': 'Unknown Patient',
    'patientDetails.medicationAdherence': 'Medication Adherence',
    'patientDetails.active': 'Active',
    'patientDetails.inactive': 'Inactive',
    'patientDetails.currentStreak': 'Current Streak',
    'patientDetails.adherenceRate': 'Adherence Rate',
    'patientDetails.noInstructions': 'No instructions',
    'patientDetails.latestReports': 'Latest Reports',
    'patientDetails.uploadedOn': 'Uploaded',
    'patientDetails.reportedSymptoms': 'Reported Symptoms',
    'patientDetails.recoveryProgress': 'Recovery Progress',
    'patientDetails.improving': 'Improving',
    'patientDetails.patientInfo': 'Patient Info',
    'patientDetails.phone': 'Phone',
    'patientDetails.addObservation': 'Add Observation',
    'patientDetails.placeholder.observation': 'Enter your observation...',
    'patientDetails.saveObservation': 'Save Observation',
    'patientDetails.observationRecorded': 'Observation recorded.',
    'patientDetails.sendSmsTo': 'Send SMS to',
    'patientDetails.noPhone': 'No phone',
    'patientDetails.sent': 'Sent!',
    'patientDetails.smsSent': 'SMS sent via Twilio.',
    'patientDetails.error.loadFailed': 'Failed to load patient data',
    'patientDetails.empty.noMeds': 'No medications found',
    'patientDetails.empty.noReports': 'No reports found',

    'login.brandSub': 'HEALTH PLATFORM',
    'login.title': 'Welcome back',
    'login.subtitle': 'Sign in to your account',
    'login.mode.email': 'Email',
    'login.mode.mobile': 'Mobile',
    'login.mode.username': 'Username',
    'login.mode.hospitalId': 'Hospital ID',
    'login.field.email': 'Email Address',
    'login.field.mobile': 'Mobile Number',
    'login.field.username': 'Username',
    'login.field.hospitalId': 'Hospital ID',
    'login.field.password': 'Password',
    'login.placeholder.password': 'Enter your password',
    'login.button.signingIn': 'Signing in...',
    'login.button.signInAs': 'Sign In as {{role}}',
    'login.error.enterPassword': 'Please enter your password.',
    'login.error.enterEmail': 'Please enter your email.',
    'login.error.enterMobile': 'Please enter your mobile number.',
    'login.error.enterUsername': 'Please enter your username.',
    'login.error.enterHospitalId': 'Please enter your hospital ID.',
    'login.error.failedDefault': 'Login failed. Please try again.',
    'login.error.failedTitle': 'Login Failed',
    'login.demo.quickAccess': 'QUICK DEMO ACCESS',
    'login.demo.modeTitle': 'Demo Mode',
    'login.demo.modeBody': 'Demo access skips authentication. For full functionality, please create an account or login.',
    'login.demo.continue': 'Continue Demo',
    'login.register.prompt': "Don't have an account?",
    'login.register.cta': 'Create account',

    'register.step.chooseRole': 'Choose role',
    'register.step.personalInfo': 'Personal info',
    'register.step.healthProfile': 'Health profile',
    'register.header.subtitle': 'Join MediVault today',
    'register.header.step': 'Step',
    'register.alert.missingFieldsTitle': 'Missing Fields',
    'register.alert.missingFieldsBody': 'Please fill in First Name, Last Name, and Email to continue.',
    'register.alert.hospitalIdRequired': 'Hospital ID is required for doctor registration.',
    'register.alert.errorTitle': 'Error',
    'register.alert.fillRequired': 'Please fill in all required fields',
    'register.alert.passwordMismatch': 'Passwords do not match',
    'register.alert.passwordMin': 'Password must be at least 8 characters',
    'register.alert.hospitalIdDoctor': 'Hospital ID is required for doctors',
    'register.role.patientDesc': 'Track health and records',
    'register.role.doctorDesc': 'Manage patients',
    'register.button.continueAs': 'Continue as {{role}}',
    'register.button.back': 'Back',
    'register.button.continue': 'Continue',
    'register.button.creating': 'Creating account...',
    'register.button.create': 'Create Account',
    'register.card.personalInfo': 'Personal information',
    'register.card.healthProfile': 'Health Profile',
    'register.card.professionalDetails': 'Professional Details',
    'register.field.firstName': 'First Name',
    'register.field.lastName': 'Last Name',
    'register.field.username': 'Username',
    'register.field.email': 'Email Address',
    'register.field.mobile': 'Mobile Number',
    'register.field.hospitalId': 'Hospital ID',
    'register.field.bloodType': 'Blood Type',
    'register.field.allergies': 'Allergies',
    'register.field.specialisation': 'Specialisation',
    'register.field.password': 'Password',
    'register.field.confirmPassword': 'Confirm Password',
    'register.summary.title': 'Account Summary',
    'register.summary.name': 'Name',
    'register.summary.role': 'Role',
    'register.login.prompt': 'Already have an account?',
    'register.login.cta': 'Sign in',

    'patient.alert.errorTitle': 'Error',
    'patient.alert.markDoseFailed': 'Failed to mark dose. Please try again.',
    'patient.greeting.morning': 'Good Morning',
    'patient.greeting.afternoon': 'Good Afternoon',
    'patient.greeting.evening': 'Good Evening',
    'patient.title': 'My Health',
    'patient.banner.scheduledToday': 'medications scheduled today',
    'patient.banner.viewSchedule': 'View Schedule',
    'patient.banner.report': 'Report',
    'patient.stats.medicines': 'Medicines',
    'patient.stats.adherence': 'Adherence',
    'patient.stats.records7d': 'Records (7d)',
    'patient.stats.alerts': 'Alerts',
    'patient.section.todaysMeds': "Today's Medications",
    'patient.section.weeklyAdherence': 'Weekly Adherence',
    'patient.section.recentReports': 'Recent Reports',
    'patient.empty.noMedsToday': 'No medications scheduled for today',
    'patient.empty.noReports': 'No reports uploaded yet',
    'patient.score.healthScore': 'Health Score',
    'patient.score.excellent': 'Excellent',
    'patient.score.good': 'Good',
    'patient.score.improving': 'Improving',
    'patient.score.dosesTaken': 'Doses Taken',
    'patient.score.pending': 'pending',
    'patient.weekly.onTrack': 'On track',
    'patient.weekly.keepGoing': 'Keep going',
    'patient.qa.symptoms': 'Symptoms',
    'patient.qa.reports': 'Reports',
    'patient.qa.medicines': 'Medicines',
    'patient.qa.qrProfile': 'QR Profile',

    'doctor.title': 'Doctor Dashboard',
    'doctor.stats.totalPatients': 'Total Patients',
    'doctor.stats.criticalAlerts': 'Critical Alerts',
    'doctor.stats.moderateAlerts': 'Moderate Alerts',
    'doctor.stats.missed24h': 'Missed (24h)',
    'doctor.section.recentAlerts': 'Recent Patient Alerts',
    'doctor.section.patientsOverview': 'Patients Overview',
    'doctor.empty.noRecentAlerts': 'No recent alerts',
    'doctor.empty.noPatients': 'No patients assigned yet',
    'doctor.empty.noPatientsHint': 'Patients will appear here when assigned',
    'doctor.qa.patients': 'Patients',
    'doctor.qa.alerts': 'Alerts',
    'doctor.qa.messages': 'Messages',
    'doctor.qa.notifications': 'Notifications',
  },

  hi: {
    'common.patient': 'मरीज',
    'common.doctor': 'डॉक्टर',
    'common.cancel': 'रद्द करें',
    'common.continue': 'जारी रखें',
    'common.language': 'भाषा',
    'common.user': 'उपयोगकर्ता',
    'common.loading': 'लोड हो रहा है...',
    'common.viewAll': 'सभी देखें',
    'common.view': 'देखें',
    'common.add': '+ जोड़ें',
    'common.retry': 'पुनः प्रयास',
    'common.error': 'त्रुटि',

    'msg.title': 'संदेश',
    'msg.subtitle': 'मरीज संचार',
    'msg.noMessagesYet': 'अभी तक कोई संदेश नहीं',
    'msg.searchPlaceholder': 'मरीज खोजें...',
    'msg.chat': 'चैट',
    'msg.typeMessage': 'संदेश लिखें...',

    'notif.title': 'सूचनाएं',
    'notif.markAll': 'सभी मार्क करें',
    'notif.unread': 'अनरीड',
    'notif.allCaughtUp': 'सब अपडेट है!',
    'notif.noneHere': 'यहां कोई सूचना नहीं है।',
    'notif.loading': 'सूचनाएं लोड हो रही हैं...',
    'notif.doctorTitle': 'डॉक्टर सूचनाएं',
    'notif.patientTitle': 'मरीज सूचनाएं',
    'notif.doctorSub': 'मरीज अलर्ट और सिस्टम अपडेट',
    'notif.patientSub': 'दवाइयां, संदेश और अपडेट',
    'notif.filter.all': 'सभी',
    'notif.filter.unread': 'अनरीड',
    'notif.filter.critical': 'गंभीर',
    'notif.filter.report': 'रिपोर्ट',
    'notif.filter.medicine': 'दवा',
    'notif.filter.message': 'संदेश',
    'notif.error.loadFailed': 'सूचनाएं लोड नहीं हो सकीं',
    'notif.error.markOne': 'रीड मार्क नहीं हो सका',
    'notif.error.markAll': 'सभी रीड मार्क नहीं हो सके',

    'patients.title': 'मरीज',
    'patients.totalPatients': 'कुल मरीज',
    'patients.loading': 'मरीज लोड हो रहे हैं...',
    'patients.critical': 'गंभीर',
    'patients.monitor': 'निगरानी में',
    'patients.stable': 'स्थिर',
    'patients.searchPlaceholder': 'नाम, स्थिति से खोजें...',
    'patients.showing': 'दिखा रहे हैं',
    'patients.of': 'में से',
    'patients.blood': 'ब्लड',
    'patients.allergies': 'एलर्जी',
    'patients.viewDetails': 'विवरण देखें',
    'patients.noPatients': 'कोई मरीज नहीं मिला',
    'patients.tryAnotherSearch': 'कोई अन्य खोज शब्द आज़माएं',

    'alerts.title': 'अलर्ट',
    'alerts.subtitle': 'कार्रवाई आवश्यक',
    'alerts.totalAlerts': 'कुल अलर्ट',
    'alerts.pending': 'लंबित',
    'alerts.responded': 'प्रतिक्रिया दी गई',
    'alerts.loading': 'अलर्ट लोड हो रहे हैं...',
    'alerts.pendingAction': 'लंबित अलर्ट - कार्रवाई आवश्यक',
    'alerts.recommended': 'सुझाव',
    'alerts.viewPatient': 'मरीज देखें',
    'alerts.sendSms': 'SMS भेजें',
    'alerts.markResponded': 'प्रतिक्रिया मार्क करें',
    'alerts.dismiss': 'हटाएं',
    'alerts.allCaughtUp': 'सब कंट्रोल में है!',
    'alerts.noPending': 'अभी कोई लंबित अलर्ट नहीं है।',
    'alerts.sendSmsViaTwilio': 'Twilio से SMS भेजें',
    'alerts.to': 'को',
    'alerts.message': 'संदेश',
    'alerts.typeMessage': 'अपना संदेश लिखें...',
    'alerts.sendViaTwilio': 'Twilio से भेजें',
    'alerts.smsSentTitle': 'SMS भेजा गया',
    'alerts.messageSentTo': 'संदेश भेजा गया',
    'alerts.viaTwilio': 'को Twilio से।',
    'alerts.loadFailed': 'अलर्ट लोड नहीं हो सके',
    'alerts.unknown': 'अज्ञात',

    'med.title': 'दवाइयां',
    'med.subtitle': 'अपनी दवाइयों को ट्रैक करें',
    'med.alert.requiredTitle': 'आवश्यक',
    'med.alert.enterMedicineName': 'दवा का नाम दर्ज करें',
    'med.alert.enterDosage': 'डोज़ दर्ज करें',
    'med.alert.successTitle': 'सफल',
    'med.alert.added': 'दवा सफलतापूर्वक जोड़ी गई',
    'med.alert.errorTitle': 'त्रुटि',
    'med.error.fetchFailed': 'दवाइयां प्राप्त नहीं हो सकीं',
    'med.error.addFailed': 'दवा जोड़ना असफल रहा',
    'med.error.markDoseFailed': 'डोज़ मार्क नहीं हो पाई',
    'med.stats.active': 'सक्रिय दवाइयां',
    'med.stats.takenToday': 'आज ली गई',
    'med.stats.pending': 'लंबित',
    'med.stats.avgAdherence': 'औसत अनुपालन',
    'med.section.todaySchedule': 'आज का शेड्यूल',
    'med.section.weeklyAdherence': 'साप्ताहिक अनुपालन',
    'med.section.myMeds': 'मेरी दवाइयां',
    'med.empty.noScheduled': 'कोई दवा निर्धारित नहीं है',
    'med.empty.noMeds': 'अभी कोई दवा नहीं जोड़ी गई',
    'med.badge.taken': 'ली गई',
    'med.action.take': 'लेें',
    'med.action.retake': 'फिर लें',
    'med.action.addMedicine': 'दवा जोड़ें',
    'med.avg': 'औसत',
    'med.noSchedule': 'कोई शेड्यूल नहीं',
    'med.started': 'शुरू',
    'med.modal.addNew': 'नई दवा जोड़ें',
    'med.field.name': 'दवा का नाम',
    'med.field.dosage': 'डोज़',
    'med.field.frequency': 'आवृत्ति',
    'med.field.timeSlots': 'समय स्लॉट',
    'med.field.instructions': 'निर्देश (वैकल्पिक)',
    'med.placeholder.name': 'जैसे: पैरासिटामोल',
    'med.placeholder.dosage': 'जैसे: 500mg',
    'med.placeholder.time': 'HH:MM',
    'med.placeholder.instructions': 'जैसे: भोजन के बाद लें',

    'login.brandSub': 'हेल्थ प्लेटफॉर्म',
    'login.title': 'फिर से स्वागत है',
    'login.subtitle': 'अपने खाते में साइन इन करें',
    'login.mode.email': 'ईमेल',
    'login.mode.mobile': 'मोबाइल',
    'login.mode.username': 'यूज़रनेम',
    'login.mode.hospitalId': 'हॉस्पिटल आईडी',
    'login.field.email': 'ईमेल पता',
    'login.field.mobile': 'मोबाइल नंबर',
    'login.field.username': 'यूज़रनेम',
    'login.field.hospitalId': 'हॉस्पिटल आईडी',
    'login.field.password': 'पासवर्ड',
    'login.placeholder.password': 'अपना पासवर्ड दर्ज करें',
    'login.button.signingIn': 'साइन इन हो रहा है...',
    'login.button.signInAs': '{{role}} के रूप में साइन इन',
    'login.error.enterPassword': 'कृपया पासवर्ड दर्ज करें।',
    'login.error.enterEmail': 'कृपया ईमेल दर्ज करें।',
    'login.error.enterMobile': 'कृपया मोबाइल नंबर दर्ज करें।',
    'login.error.enterUsername': 'कृपया यूज़रनेम दर्ज करें।',
    'login.error.enterHospitalId': 'कृपया हॉस्पिटल आईडी दर्ज करें।',
    'login.error.failedDefault': 'लॉगिन असफल रहा। कृपया फिर प्रयास करें।',
    'login.error.failedTitle': 'लॉगिन असफल',
    'login.demo.quickAccess': 'त्वरित डेमो एक्सेस',
    'login.demo.modeTitle': 'डेमो मोड',
    'login.demo.modeBody': 'डेमो एक्सेस में प्रमाणीकरण नहीं होता। पूरी सुविधाओं के लिए खाता बनाएं या लॉगिन करें।',
    'login.demo.continue': 'डेमो जारी रखें',
    'login.register.prompt': 'क्या आपका खाता नहीं है?',
    'login.register.cta': 'खाता बनाएं',

    'register.step.chooseRole': 'भूमिका चुनें',
    'register.step.personalInfo': 'व्यक्तिगत जानकारी',
    'register.step.healthProfile': 'स्वास्थ्य प्रोफाइल',
    'register.header.subtitle': 'आज ही MediVault से जुड़ें',
    'register.header.step': 'स्टेप',
    'register.alert.missingFieldsTitle': 'जानकारी अधूरी है',
    'register.alert.missingFieldsBody': 'कृपया First Name, Last Name और Email भरें।',
    'register.alert.hospitalIdRequired': 'डॉक्टर रजिस्ट्रेशन के लिए Hospital ID आवश्यक है।',
    'register.alert.errorTitle': 'त्रुटि',
    'register.alert.fillRequired': 'कृपया सभी आवश्यक फ़ील्ड भरें',
    'register.alert.passwordMismatch': 'पासवर्ड मेल नहीं खाते',
    'register.alert.passwordMin': 'पासवर्ड कम से कम 8 अक्षरों का होना चाहिए',
    'register.alert.hospitalIdDoctor': 'डॉक्टर के लिए Hospital ID आवश्यक है',
    'register.role.patientDesc': 'स्वास्थ्य और रिकॉर्ड ट्रैक करें',
    'register.role.doctorDesc': 'मरीज प्रबंधन करें',
    'register.button.continueAs': '{{role}} के रूप में जारी रखें',
    'register.button.back': 'वापस',
    'register.button.continue': 'जारी रखें',
    'register.button.creating': 'खाता बनाया जा रहा है...',
    'register.button.create': 'खाता बनाएं',
    'register.card.personalInfo': 'व्यक्तिगत जानकारी',
    'register.card.healthProfile': 'स्वास्थ्य प्रोफाइल',
    'register.card.professionalDetails': 'पेशेवर विवरण',
    'register.field.firstName': 'पहला नाम',
    'register.field.lastName': 'अंतिम नाम',
    'register.field.username': 'यूज़रनेम',
    'register.field.email': 'ईमेल पता',
    'register.field.mobile': 'मोबाइल नंबर',
    'register.field.hospitalId': 'हॉस्पिटल आईडी',
    'register.field.bloodType': 'ब्लड ग्रुप',
    'register.field.allergies': 'एलर्जी',
    'register.field.specialisation': 'विशेषज्ञता',
    'register.field.password': 'पासवर्ड',
    'register.field.confirmPassword': 'पासवर्ड की पुष्टि करें',
    'register.summary.title': 'खाता सारांश',
    'register.summary.name': 'नाम',
    'register.summary.role': 'भूमिका',
    'register.login.prompt': 'पहले से खाता है?',
    'register.login.cta': 'साइन इन',

    'patient.alert.errorTitle': 'त्रुटि',
    'patient.alert.markDoseFailed': 'डोज़ मार्क नहीं हो पाई। कृपया फिर प्रयास करें।',
    'patient.greeting.morning': 'सुप्रभात',
    'patient.greeting.afternoon': 'नमस्कार',
    'patient.greeting.evening': 'शुभ संध्या',
    'patient.title': 'मेरा स्वास्थ्य',
    'patient.banner.scheduledToday': 'दवाइयां आज निर्धारित हैं',
    'patient.banner.viewSchedule': 'शेड्यूल देखें',
    'patient.banner.report': 'रिपोर्ट',
    'patient.stats.medicines': 'दवाइयां',
    'patient.stats.adherence': 'अनुपालन',
    'patient.stats.records7d': 'रिकॉर्ड (7 दिन)',
    'patient.stats.alerts': 'अलर्ट',
    'patient.section.todaysMeds': 'आज की दवाइयां',
    'patient.section.weeklyAdherence': 'साप्ताहिक अनुपालन',
    'patient.section.recentReports': 'हाल की रिपोर्टें',
    'patient.empty.noMedsToday': 'आज के लिए कोई दवा निर्धारित नहीं है',
    'patient.empty.noReports': 'अभी तक कोई रिपोर्ट अपलोड नहीं हुई',
    'patient.score.healthScore': 'हेल्थ स्कोर',
    'patient.score.excellent': 'बेहतर',
    'patient.score.good': 'अच्छा',
    'patient.score.improving': 'सुधार हो रहा है',
    'patient.score.dosesTaken': 'ली गई डोज़',
    'patient.score.pending': 'बाकी',
    'patient.weekly.onTrack': 'सही ट्रैक पर',
    'patient.weekly.keepGoing': 'जारी रखें',
    'patient.qa.symptoms': 'लक्षण',
    'patient.qa.reports': 'रिपोर्ट',
    'patient.qa.medicines': 'दवाइयां',
    'patient.qa.qrProfile': 'क्यूआर प्रोफाइल',

    'doctor.title': 'डॉक्टर डैशबोर्ड',
    'doctor.stats.totalPatients': 'कुल मरीज',
    'doctor.stats.criticalAlerts': 'गंभीर अलर्ट',
    'doctor.stats.moderateAlerts': 'मध्यम अलर्ट',
    'doctor.stats.missed24h': 'मिस्ड (24 घंटे)',
    'doctor.section.recentAlerts': 'हाल के मरीज अलर्ट',
    'doctor.section.patientsOverview': 'मरीज अवलोकन',
    'doctor.empty.noRecentAlerts': 'हाल में कोई अलर्ट नहीं',
    'doctor.empty.noPatients': 'अभी तक कोई मरीज असाइन नहीं है',
    'doctor.empty.noPatientsHint': 'असाइन होने पर मरीज यहां दिखेंगे',
    'doctor.qa.patients': 'मरीज',
    'doctor.qa.alerts': 'अलर्ट',
    'doctor.qa.messages': 'संदेश',
    'doctor.qa.notifications': 'सूचनाएं',
  },

  ta: {
    'common.patient': 'நோயாளர்',
    'common.doctor': 'மருத்துவர்',
    'common.cancel': 'ரத்து',
    'common.continue': 'தொடரவும்',
    'common.language': 'மொழி',
    'common.user': 'பயனர்',
    'common.loading': 'ஏற்றப்படுகிறது...',
    'common.viewAll': 'அனைத்தையும் காண்',
    'common.view': 'காண்',
    'common.add': '+ சேர்',
    'common.retry': 'மீண்டும் முயற்சி',
    'common.error': 'பிழை',

    'msg.title': 'செய்திகள்',
    'msg.subtitle': 'நோயாளர் தொடர்புகள்',
    'msg.noMessagesYet': 'இன்னும் செய்திகள் இல்லை',
    'msg.searchPlaceholder': 'நோயாளிகளை தேடு...',
    'msg.chat': 'அரட்டை',
    'msg.typeMessage': 'செய்தி எழுதவும்...',

    'notif.title': 'அறிவிப்புகள்',
    'notif.markAll': 'அனைத்தையும் குறி',
    'notif.unread': 'படிக்காதவை',
    'notif.allCaughtUp': 'அனைத்தும் புதுப்பிக்கப்பட்டது!',
    'notif.noneHere': 'இங்கு அறிவிப்புகள் இல்லை.',
    'notif.loading': 'அறிவிப்புகள் ஏற்றப்படுகிறது...',
    'notif.doctorTitle': 'மருத்துவர் அறிவிப்புகள்',
    'notif.patientTitle': 'நோயாளர் அறிவிப்புகள்',
    'notif.doctorSub': 'நோயாளர் எச்சரிக்கைகள் மற்றும் அமைப்பு புதுப்பிப்புகள்',
    'notif.patientSub': 'மருந்துகள், செய்திகள் மற்றும் புதுப்பிப்புகள்',
    'notif.filter.all': 'அனைத்தும்',
    'notif.filter.unread': 'படிக்காதவை',
    'notif.filter.critical': 'அவசரம்',
    'notif.filter.report': 'அறிக்கை',
    'notif.filter.medicine': 'மருந்து',
    'notif.filter.message': 'செய்தி',
    'notif.error.loadFailed': 'அறிவிப்புகளை ஏற்ற முடியவில்லை',
    'notif.error.markOne': 'படித்ததாக குறிக்க முடியவில்லை',
    'notif.error.markAll': 'அனைத்தையும் குறிக்க முடியவில்லை',

    'patients.title': 'நோயாளிகள்',
    'patients.totalPatients': 'மொத்த நோயாளிகள்',
    'patients.loading': 'நோயாளிகள் ஏற்றப்படுகிறது...',
    'patients.critical': 'அவசரம்',
    'patients.monitor': 'கண்காணிப்பில்',
    'patients.stable': 'நிலையான',
    'patients.searchPlaceholder': 'பெயர், நிலை மூலம் தேடு...',
    'patients.showing': 'காண்பிக்கப்படுகிறது',
    'patients.of': 'இல்',
    'patients.blood': 'இரத்தம்',
    'patients.allergies': 'அலர்ஜிகள்',
    'patients.viewDetails': 'விவரங்கள் காண்',
    'patients.noPatients': 'நோயாளிகள் கிடைக்கவில்லை',
    'patients.tryAnotherSearch': 'வேறு தேடலை முயற்சிக்கவும்',

    'alerts.title': 'எச்சரிக்கைகள்',
    'alerts.subtitle': 'நடவடிக்கை தேவை',
    'alerts.totalAlerts': 'மொத்த எச்சரிக்கைகள்',
    'alerts.pending': 'நிலுவை',
    'alerts.responded': 'பதில் அளிக்கப்பட்டது',
    'alerts.loading': 'எச்சரிக்கைகள் ஏற்றப்படுகிறது...',
    'alerts.pendingAction': 'நிலுவை எச்சரிக்கைகள் - உடனடி நடவடிக்கை',
    'alerts.recommended': 'பரிந்துரை',
    'alerts.viewPatient': 'நோயாளர் விவரம்',
    'alerts.sendSms': 'SMS அனுப்பு',
    'alerts.markResponded': 'பதில் அளிக்கப்பட்டது என குறி',
    'alerts.dismiss': 'நீக்கு',
    'alerts.allCaughtUp': 'அனைத்தும் சரியாக உள்ளது!',
    'alerts.noPending': 'இப்போது நிலுவை எச்சரிக்கைகள் இல்லை.',
    'alerts.sendSmsViaTwilio': 'Twilio மூலம் SMS அனுப்பு',
    'alerts.to': 'பெறுநர்',
    'alerts.message': 'செய்தி',
    'alerts.typeMessage': 'உங்கள் செய்தியை எழுதவும்...',
    'alerts.sendViaTwilio': 'Twilio வழியாக அனுப்பு',
    'alerts.smsSentTitle': 'SMS அனுப்பப்பட்டது',
    'alerts.messageSentTo': 'செய்தி அனுப்பப்பட்டது',
    'alerts.viaTwilio': 'Twilio வழியாக.',
    'alerts.loadFailed': 'எச்சரிக்கைகளை ஏற்ற முடியவில்லை',
    'alerts.unknown': 'தெரியாது',

    'med.title': 'மருந்துகள்',
    'med.subtitle': 'உங்கள் மருந்துகளை கண்காணிக்கவும்',
    'med.alert.requiredTitle': 'தேவை',
    'med.alert.enterMedicineName': 'மருந்து பெயரை உள்ளிடவும்',
    'med.alert.enterDosage': 'அளவை உள்ளிடவும்',
    'med.alert.successTitle': 'வெற்றி',
    'med.alert.added': 'மருந்து வெற்றிகரமாக சேர்க்கப்பட்டது',
    'med.alert.errorTitle': 'பிழை',
    'med.error.fetchFailed': 'மருந்துகளை பெற முடியவில்லை',
    'med.error.addFailed': 'மருந்து சேர்க்க முடியவில்லை',
    'med.error.markDoseFailed': 'டோஸ் குறிக்க முடியவில்லை',
    'med.stats.active': 'செயலில் உள்ள மருந்துகள்',
    'med.stats.takenToday': 'இன்று எடுத்தது',
    'med.stats.pending': 'நிலுவை',
    'med.stats.avgAdherence': 'சராசரி பின்பற்றல்',
    'med.section.todaySchedule': 'இன்றைய அட்டவணை',
    'med.section.weeklyAdherence': 'வாராந்திர பின்பற்றல்',
    'med.section.myMeds': 'என் மருந்துகள்',
    'med.empty.noScheduled': 'மருந்து அட்டவணை இல்லை',
    'med.empty.noMeds': 'இன்னும் மருந்துகள் சேர்க்கப்படவில்லை',
    'med.badge.taken': 'எடுத்தது',
    'med.action.take': 'எடு',
    'med.action.retake': 'மீண்டும் எடு',
    'med.action.addMedicine': 'மருந்து சேர்',
    'med.avg': 'சராசரி',
    'med.noSchedule': 'அட்டவணை இல்லை',
    'med.started': 'தொடக்கம்',
    'med.modal.addNew': 'புதிய மருந்து சேர்',
    'med.field.name': 'மருந்து பெயர்',
    'med.field.dosage': 'அளவு',
    'med.field.frequency': 'அடிக்கடி',
    'med.field.timeSlots': 'நேர இடைவெளிகள்',
    'med.field.instructions': 'வழிமுறைகள் (விருப்பம்)',
    'med.placeholder.name': 'எ.கா. பாராசிட்டமால்',
    'med.placeholder.dosage': 'எ.கா. 500mg',
    'med.placeholder.time': 'HH:MM',
    'med.placeholder.instructions': 'எ.கா. உணவுக்குப் பிறகு எடுக்கவும்',

    'login.brandSub': 'சுகாதார தளம்',
    'login.title': 'மீண்டும் வரவேற்கிறோம்',
    'login.subtitle': 'உங்கள் கணக்கில் உள்நுழைக',
    'login.mode.email': 'மின்னஞ்சல்',
    'login.mode.mobile': 'மொபைல்',
    'login.mode.username': 'பயனர் பெயர்',
    'login.mode.hospitalId': 'மருத்துவமனை ஐடி',
    'login.field.email': 'மின்னஞ்சல் முகவரி',
    'login.field.mobile': 'மொபைல் எண்',
    'login.field.username': 'பயனர் பெயர்',
    'login.field.hospitalId': 'மருத்துவமனை ஐடி',
    'login.field.password': 'கடவுச்சொல்',
    'login.placeholder.password': 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
    'login.button.signingIn': 'உள்நுழைகிறது...',
    'login.button.signInAs': '{{role}} ஆக உள்நுழைக',
    'login.error.enterPassword': 'கடவுச்சொல்லை உள்ளிடவும்.',
    'login.error.enterEmail': 'மின்னஞ்சலை உள்ளிடவும்.',
    'login.error.enterMobile': 'மொபைல் எண்ணை உள்ளிடவும்.',
    'login.error.enterUsername': 'பயனர் பெயரை உள்ளிடவும்.',
    'login.error.enterHospitalId': 'மருத்துவமனை ஐடியை உள்ளிடவும்.',
    'login.error.failedDefault': 'உள்நுழைவு தோல்வி. மீண்டும் முயற்சிக்கவும்.',
    'login.error.failedTitle': 'உள்நுழைவு தோல்வி',
    'login.demo.quickAccess': 'விரைவு டெமோ அணுகல்',
    'login.demo.modeTitle': 'டெமோ முறை',
    'login.demo.modeBody': 'டெமோவில் அங்கீகாரம் தவிர்க்கப்படும். முழு வசதிக்கு கணக்கு உருவாக்கவும் அல்லது உள்நுழையவும்.',
    'login.demo.continue': 'டெமோ தொடரவும்',
    'login.register.prompt': 'கணக்கு இல்லையா?',
    'login.register.cta': 'கணக்கு உருவாக்கு',

    'register.step.chooseRole': 'பாத்திரத்தை தேர்வு செய்',
    'register.step.personalInfo': 'தனிப்பட்ட தகவல்',
    'register.step.healthProfile': 'ஆரோக்கிய சுயவிவரம்',
    'register.header.subtitle': 'இன்றே MediVault-இல் சேருங்கள்',
    'register.header.step': 'படி',
    'register.alert.missingFieldsTitle': 'புலங்கள் பூர்த்தி செய்யப்படவில்லை',
    'register.alert.missingFieldsBody': 'First Name, Last Name மற்றும் Email நிரப்பவும்.',
    'register.alert.hospitalIdRequired': 'மருத்துவர் பதிவு செய்ய Hospital ID அவசியம்.',
    'register.alert.errorTitle': 'பிழை',
    'register.alert.fillRequired': 'அனைத்து கட்டாய புலங்களையும் நிரப்பவும்',
    'register.alert.passwordMismatch': 'கடவுச்சொற்கள் பொருந்தவில்லை',
    'register.alert.passwordMin': 'கடவுச்சொல் குறைந்தது 8 எழுத்துகள் இருக்க வேண்டும்',
    'register.alert.hospitalIdDoctor': 'மருத்துவருக்கு Hospital ID அவசியம்',
    'register.role.patientDesc': 'உடல்நலம் மற்றும் பதிவுகளை கண்காணிக்கவும்',
    'register.role.doctorDesc': 'நோயாளிகளை நிர்வகிக்கவும்',
    'register.button.continueAs': '{{role}} ஆக தொடரவும்',
    'register.button.back': 'பின்',
    'register.button.continue': 'தொடரவும்',
    'register.button.creating': 'கணக்கு உருவாக்கப்படுகிறது...',
    'register.button.create': 'கணக்கு உருவாக்கு',
    'register.card.personalInfo': 'தனிப்பட்ட தகவல்',
    'register.card.healthProfile': 'ஆரோக்கிய சுயவிவரம்',
    'register.card.professionalDetails': 'தொழில்முறை விவரங்கள்',
    'register.field.firstName': 'முதல் பெயர்',
    'register.field.lastName': 'கடைசி பெயர்',
    'register.field.username': 'பயனர் பெயர்',
    'register.field.email': 'மின்னஞ்சல் முகவரி',
    'register.field.mobile': 'மொபைல் எண்',
    'register.field.hospitalId': 'மருத்துவமனை ஐடி',
    'register.field.bloodType': 'ரத்த வகை',
    'register.field.allergies': 'அலர்ஜிகள்',
    'register.field.specialisation': 'நிபுணத்துவம்',
    'register.field.password': 'கடவுச்சொல்',
    'register.field.confirmPassword': 'கடவுச்சொல் உறுதிப்படுத்தல்',
    'register.summary.title': 'கணக்கு சுருக்கம்',
    'register.summary.name': 'பெயர்',
    'register.summary.role': 'பாத்திரம்',
    'register.login.prompt': 'ஏற்கனவே கணக்கு உள்ளதா?',
    'register.login.cta': 'உள்நுழைக',

    'patient.alert.errorTitle': 'பிழை',
    'patient.alert.markDoseFailed': 'மருந்து பதிவு செய்ய முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    'patient.greeting.morning': 'காலை வணக்கம்',
    'patient.greeting.afternoon': 'மதிய வணக்கம்',
    'patient.greeting.evening': 'மாலை வணக்கம்',
    'patient.title': 'என் உடல்நலம்',
    'patient.banner.scheduledToday': 'மருந்துகள் இன்று திட்டமிடப்பட்டுள்ளன',
    'patient.banner.viewSchedule': 'அட்டவணையை காண்',
    'patient.banner.report': 'அறிக்கை',
    'patient.stats.medicines': 'மருந்துகள்',
    'patient.stats.adherence': 'பின்பற்றல்',
    'patient.stats.records7d': 'பதிவுகள் (7 நாள்)',
    'patient.stats.alerts': 'அலர்ட்கள்',
    'patient.section.todaysMeds': 'இன்றைய மருந்துகள்',
    'patient.section.weeklyAdherence': 'வாராந்திர பின்பற்றல்',
    'patient.section.recentReports': 'சமீபத்திய அறிக்கைகள்',
    'patient.empty.noMedsToday': 'இன்றைக்கு மருந்து அட்டவணை இல்லை',
    'patient.empty.noReports': 'இன்னும் அறிக்கைகள் பதிவேற்றப்படவில்லை',
    'patient.score.healthScore': 'ஆரோக்கிய மதிப்பெண்',
    'patient.score.excellent': 'சிறப்பு',
    'patient.score.good': 'நன்று',
    'patient.score.improving': 'மேம்பட்டு வருகிறது',
    'patient.score.dosesTaken': 'எடுத்த டோஸ்கள்',
    'patient.score.pending': 'நிலுவை',
    'patient.weekly.onTrack': 'சரியான பாதையில்',
    'patient.weekly.keepGoing': 'தொடருங்கள்',
    'patient.qa.symptoms': 'அறிகுறிகள்',
    'patient.qa.reports': 'அறிக்கைகள்',
    'patient.qa.medicines': 'மருந்துகள்',
    'patient.qa.qrProfile': 'QR சுயவிவரம்',

    'doctor.title': 'மருத்துவர் டாஷ்போர்டு',
    'doctor.stats.totalPatients': 'மொத்த நோயாளிகள்',
    'doctor.stats.criticalAlerts': 'அவசர அலர்ட்கள்',
    'doctor.stats.moderateAlerts': 'மிதமான அலர்ட்கள்',
    'doctor.stats.missed24h': 'தவறியது (24 மணி)',
    'doctor.section.recentAlerts': 'சமீபத்திய நோயாளர் அலர்ட்கள்',
    'doctor.section.patientsOverview': 'நோயாளர் கண்ணோட்டம்',
    'doctor.empty.noRecentAlerts': 'சமீபத்திய அலர்ட்கள் இல்லை',
    'doctor.empty.noPatients': 'இன்னும் நோயாளிகள் ஒதுக்கப்படவில்லை',
    'doctor.empty.noPatientsHint': 'ஒதுக்கப்பட்டதும் இங்கே தோன்றும்',
    'doctor.qa.patients': 'நோயாளிகள்',
    'doctor.qa.alerts': 'அலர்ட்கள்',
    'doctor.qa.messages': 'செய்திகள்',
    'doctor.qa.notifications': 'அறிவிப்புகள்',
  },

  kn: {
    'common.patient': 'ರೋಗಿ',
    'common.doctor': 'ವೈದ್ಯರು',
    'common.cancel': 'ರದ್ದು',
    'common.continue': 'ಮುಂದುವರಿಸಿ',
    'common.language': 'ಭಾಷೆ',
    'common.user': 'ಬಳಕೆದಾರ',
    'common.loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    'common.viewAll': 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
    'common.view': 'ನೋಡಿ',
    'common.add': '+ ಸೇರಿಸಿ',
    'common.retry': 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    'common.error': 'ದೋಷ',
    'msg.title': 'ಸಂದೇಶಗಳು',
    'msg.subtitle': 'ರೋಗಿ ಸಂವಹನ',
    'msg.noMessagesYet': 'ಇನ್ನೂ ಸಂದೇಶಗಳಿಲ್ಲ',
    'msg.searchPlaceholder': 'ರೋಗಿಗಳನ್ನು ಹುಡುಕಿ...',
    'msg.chat': 'ಚಾಟ್',
    'msg.typeMessage': 'ಸಂದೇಶ ಬರೆಯಿರಿ...',
    'notif.title': 'ಅಧಿಸೂಚನೆಗಳು',
    'notif.markAll': 'ಎಲ್ಲವನ್ನೂ ಗುರುತುಮಾಡಿ',
    'notif.unread': 'ಓದದವು',
    'notif.allCaughtUp': 'ಎಲ್ಲವೂ ಓದಲಾಗಿದೆ!',
    'notif.noneHere': 'ಇಲ್ಲಿ ಯಾವುದೇ ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ.',
    'notif.loading': 'ಅಧಿಸೂಚನೆಗಳು ಲೋಡ್ ಆಗುತ್ತಿವೆ...',
    'notif.doctorTitle': 'ವೈದ್ಯರ ಅಧಿಸೂಚನೆಗಳು',
    'notif.patientTitle': 'ರೋಗಿಯ ಅಧಿಸೂಚನೆಗಳು',
    'notif.doctorSub': 'ರೋಗಿ ಎಚ್ಚರಿಕೆಗಳು ಮತ್ತು ವ್ಯವಸ್ಥೆ ನವೀಕರಣಗಳು',
    'notif.patientSub': 'ಔಷಧಿ, ಸಂದೇಶಗಳು ಮತ್ತು ನವೀಕರಣಗಳು',
    'notif.filter.all': 'ಎಲ್ಲ',
    'notif.filter.unread': 'ಓದದವು',
    'notif.filter.critical': 'ಗಂಭೀರ',
    'notif.filter.report': 'ವರದಿ',
    'notif.filter.medicine': 'ಔಷಧಿ',
    'notif.filter.message': 'ಸಂದೇಶ',
    'notif.error.loadFailed': 'ಅಧಿಸೂಚನೆಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ವಿಫಲ',
    'notif.error.markOne': 'ಓದಿದೆ ಎಂದು ಗುರುತಿಸಲು ವಿಫಲ',
    'notif.error.markAll': 'ಎಲ್ಲವನ್ನೂ ಗುರುತಿಸಲು ವಿಫಲ',
    'patients.title': 'ರೋಗಿಗಳು',
    'patients.totalPatients': 'ಒಟ್ಟು ರೋಗಿಗಳು',
    'patients.loading': 'ರೋಗಿಗಳು ಲೋಡ್ ಆಗುತ್ತಿದ್ದಾರೆ...',
    'patients.critical': 'ಗಂಭೀರ',
    'patients.monitor': 'ನಿಗಾದಲ್ಲಿ',
    'patients.stable': 'ಸ್ಥಿರ',
    'patients.searchPlaceholder': 'ಹೆಸರು, ಸ್ಥಿತಿಯಿಂದ ಹುಡುಕಿ...',
    'patients.showing': 'ತೋರಿಸಲಾಗುತ್ತಿದೆ',
    'patients.of': 'ನಲ್ಲಿ',
    'patients.blood': 'ರಕ್ತ',
    'patients.allergies': 'ಅಲರ್ಜಿ',
    'patients.viewDetails': 'ವಿವರ ನೋಡಿ',
    'patients.noPatients': 'ರೋಗಿಗಳು ಸಿಕ್ಕಿಲ್ಲ',
    'patients.tryAnotherSearch': 'ಬೇರೆ ಹುಡುಕಾಟ ಪ್ರಯತ್ನಿಸಿ',
    'alerts.title': 'ಎಚ್ಚರಿಕೆಗಳು',
    'alerts.subtitle': 'ಕ್ರಮ ಅಗತ್ಯ',
    'alerts.totalAlerts': 'ಒಟ್ಟು ಎಚ್ಚರಿಕೆಗಳು',
    'alerts.pending': 'ಬಾಕಿ',
    'alerts.responded': 'ಪ್ರತಿಕ್ರಿಯಿಸಲಾಗಿದೆ',
    'alerts.loading': 'ಎಚ್ಚರಿಕೆಗಳು ಲೋಡ್ ಆಗುತ್ತಿವೆ...',
    'alerts.pendingAction': 'ಬಾಕಿ ಎಚ್ಚರಿಕೆಗಳು - ತಕ್ಷಣ ಕ್ರಮ',
    'alerts.recommended': 'ಶಿಫಾರಸು',
    'alerts.viewPatient': 'ರೋಗಿ ವಿವರ',
    'alerts.sendSms': 'SMS ಕಳುಹಿಸಿ',
    'alerts.markResponded': 'ಪ್ರತಿಕ್ರಿಯಿಸಲಾಗಿದೆ ಎಂದು ಗುರುತು',
    'alerts.dismiss': 'ಅಳಿಸಿ',
    'alerts.allCaughtUp': 'ಎಲ್ಲವೂ ನಿಯಂತ್ರಣದಲ್ಲಿ!',
    'alerts.noPending': 'ಈಗ ಯಾವುದೇ ಬಾಕಿ ಎಚ್ಚರಿಕೆಗಳಿಲ್ಲ.',
    'alerts.sendSmsViaTwilio': 'Twilio ಮೂಲಕ SMS ಕಳುಹಿಸಿ',
    'alerts.to': 'ಗೆ',
    'alerts.message': 'ಸಂದೇಶ',
    'alerts.typeMessage': 'ನಿಮ್ಮ ಸಂದೇಶ ಬರೆಯಿರಿ...',
    'alerts.sendViaTwilio': 'Twilio ಮೂಲಕ ಕಳುಹಿಸಿ',
    'alerts.smsSentTitle': 'SMS ಕಳುಹಿಸಲಾಗಿದೆ',
    'alerts.messageSentTo': 'ಸಂದೇಶ ಕಳುಹಿಸಲಾಗಿದೆ',
    'alerts.viaTwilio': 'ಗೆ Twilio ಮೂಲಕ.',
    'alerts.loadFailed': 'ಎಚ್ಚರಿಕೆಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ವಿಫಲ',
    'alerts.unknown': 'ಅಪರಿಚಿತ',
    'med.title': 'ಔಷಧಿಗಳು',
    'med.subtitle': 'ನಿಮ್ಮ ಔಷಧಿಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    'med.alert.requiredTitle': 'ಅಗತ್ಯ',
    'med.alert.enterMedicineName': 'ಔಷಧಿಯ ಹೆಸರು ನಮೂದಿಸಿ',
    'med.alert.enterDosage': 'ಡೋಸ್ ನಮೂದಿಸಿ',
    'med.alert.successTitle': 'ಯಶಸ್ಸು',
    'med.alert.added': 'ಔಷಧಿ ಯಶಸ್ವಿಯಾಗಿ ಸೇರಿಸಲಾಗಿದೆ',
    'med.alert.errorTitle': 'ದೋಷ',
    'med.error.fetchFailed': 'ಔಷಧಿ ವಿವರ ಪಡೆಯಲು ವಿಫಲ',
    'med.error.addFailed': 'ಔಷಧಿ ಸೇರಿಸಲು ವಿಫಲ',
    'med.error.markDoseFailed': 'ಡೋಸ್ ಗುರುತಿಸಲು ವಿಫಲ',
    'med.stats.active': 'ಸಕ್ರಿಯ ಔಷಧಿಗಳು',
    'med.stats.takenToday': 'ಇಂದು ತೆಗೆದುಕೊಂಡವು',
    'med.stats.pending': 'ಬಾಕಿ',
    'med.stats.avgAdherence': 'ಸರಾಸರಿ ಅನುಸರಣೆ',
    'med.section.todaySchedule': 'ಇಂದಿನ ವೇಳಾಪಟ್ಟಿ',
    'med.section.weeklyAdherence': 'ವಾರದ ಅನುಸರಣೆ',
    'med.section.myMeds': 'ನನ್ನ ಔಷಧಿಗಳು',
    'med.empty.noScheduled': 'ಔಷಧಿ ವೇಳಾಪಟ್ಟಿ ಇಲ್ಲ',
    'med.empty.noMeds': 'ಇನ್ನೂ ಔಷಧಿ ಸೇರಿಸಲಿಲ್ಲ',
    'med.badge.taken': 'ತೆಗೆದುಕೊಂಡಿದೆ',
    'med.action.take': 'ತೆಗೆದುಕೊಳ್ಳಿ',
    'med.action.retake': 'ಮತ್ತೆ ತೆಗೆದುಕೊಳ್ಳಿ',
    'med.action.addMedicine': 'ಔಷಧಿ ಸೇರಿಸಿ',
    'med.avg': 'ಸರಾಸರಿ',
    'med.noSchedule': 'ವೇಳಾಪಟ್ಟಿ ಇಲ್ಲ',
    'med.started': 'ಪ್ರಾರಂಭ',
    'med.modal.addNew': 'ಹೊಸ ಔಷಧಿ ಸೇರಿಸಿ',
    'med.field.name': 'ಔಷಧಿ ಹೆಸರು',
    'med.field.dosage': 'ಡೋಸ್',
    'med.field.frequency': 'ಆವೃತ್ತಿ',
    'med.field.timeSlots': 'ಸಮಯ ಸ್ಲಾಟ್‌ಗಳು',
    'med.field.instructions': 'ಸೂಚನೆಗಳು (ಐಚ್ಛಿಕ)',
    'med.placeholder.name': 'ಉದಾ. ಪ್ಯಾರಾಸಿಟಮಾಲ್',
    'med.placeholder.dosage': 'ಉದಾ. 500mg',
    'med.placeholder.time': 'HH:MM',
    'med.placeholder.instructions': 'ಉದಾ. ಊಟದ ನಂತರ ತೆಗೆದುಕೊಳ್ಳಿ',

    'login.brandSub': 'ಹೆಲ್ತ್ ಪ್ಲ್ಯಾಟ್‌ಫಾರ್ಮ್',
    'login.title': 'ಮತ್ತೆ ಸ್ವಾಗತ',
    'login.subtitle': 'ನಿಮ್ಮ ಖಾತೆಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    'login.mode.email': 'ಇಮೇಲ್',
    'login.mode.mobile': 'ಮೊಬೈಲ್',
    'login.mode.username': 'ಬಳಕೆದಾರ ಹೆಸರು',
    'login.mode.hospitalId': 'ಆಸ್ಪತ್ರೆ ಐಡಿ',
    'login.field.email': 'ಇಮೇಲ್ ವಿಳಾಸ',
    'login.field.mobile': 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    'login.field.username': 'ಬಳಕೆದಾರ ಹೆಸರು',
    'login.field.hospitalId': 'ಆಸ್ಪತ್ರೆ ಐಡಿ',
    'login.field.password': 'ಪಾಸ್ವರ್ಡ್',
    'login.placeholder.password': 'ನಿಮ್ಮ ಪಾಸ್ವರ್ಡ್ ನಮೂದಿಸಿ',
    'login.button.signingIn': 'ಸೈನ್ ಇನ್ ಆಗುತ್ತಿದೆ...',
    'login.button.signInAs': '{{role}} ಆಗಿ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    'login.error.enterPassword': 'ದಯವಿಟ್ಟು ಪಾಸ್ವರ್ಡ್ ನಮೂದಿಸಿ.',
    'login.error.enterEmail': 'ದಯವಿಟ್ಟು ಇಮೇಲ್ ನಮೂದಿಸಿ.',
    'login.error.enterMobile': 'ದಯವಿಟ್ಟು ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ.',
    'login.error.enterUsername': 'ದಯವಿಟ್ಟು ಬಳಕೆದಾರ ಹೆಸರು ನಮೂದಿಸಿ.',
    'login.error.enterHospitalId': 'ದಯವಿಟ್ಟು ಆಸ್ಪತ್ರೆ ಐಡಿ ನಮೂದಿಸಿ.',
    'login.error.failedDefault': 'ಲಾಗಿನ್ ವಿಫಲವಾಗಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    'login.error.failedTitle': 'ಲಾಗಿನ್ ವಿಫಲ',
    'login.demo.quickAccess': 'ಶೀಘ್ರ ಡೆಮೋ ಪ್ರವೇಶ',
    'login.demo.modeTitle': 'ಡೆಮೋ ಮೋಡ್',
    'login.demo.modeBody': 'ಡೆಮೋದಲ್ಲಿ ದೃಢೀಕರಣವನ್ನು ಬಿಟ್ಟುಬಿಡಲಾಗುತ್ತದೆ. ಸಂಪೂರ್ಣ ಬಳಕೆಗಾಗಿ ಖಾತೆ ರಚಿಸಿ ಅಥವಾ ಲಾಗಿನ್ ಮಾಡಿ.',
    'login.demo.continue': 'ಡೆಮೋ ಮುಂದುವರಿಸಿ',
    'login.register.prompt': 'ಖಾತೆ ಇಲ್ಲವೇ?',
    'login.register.cta': 'ಖಾತೆ ರಚಿಸಿ',

    'register.step.chooseRole': 'ಪಾತ್ರ ಆಯ್ಕೆಮಾಡಿ',
    'register.step.personalInfo': 'ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ',
    'register.step.healthProfile': 'ಆರೋಗ್ಯ ಪ್ರೊಫೈಲ್',
    'register.header.subtitle': 'ಇಂದೇ MediVault ಸೇರಿ',
    'register.header.step': 'ಹಂತ',
    'register.alert.missingFieldsTitle': 'ಮಾಹಿತಿ ಅಪೂರ್ಣವಾಗಿದೆ',
    'register.alert.missingFieldsBody': 'First Name, Last Name ಮತ್ತು Email ತುಂಬಿ.',
    'register.alert.hospitalIdRequired': 'ವೈದ್ಯರ ನೋಂದಣಿಗೆ Hospital ID ಅಗತ್ಯ.',
    'register.alert.errorTitle': 'ದೋಷ',
    'register.alert.fillRequired': 'ದಯವಿಟ್ಟು ಎಲ್ಲಾ ಕಡ್ಡಾಯ ಮಾಹಿತಿಯನ್ನು ತುಂಬಿ',
    'register.alert.passwordMismatch': 'ಪಾಸ್ವರ್ಡ್‌ಗಳು ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ',
    'register.alert.passwordMin': 'ಪಾಸ್ವರ್ಡ್ ಕನಿಷ್ಠ 8 ಅಕ್ಷರಗಳು ಇರಬೇಕು',
    'register.alert.hospitalIdDoctor': 'ವೈದ್ಯರಿಗೆ Hospital ID ಅಗತ್ಯ',
    'register.role.patientDesc': 'ಆರೋಗ್ಯ ಮತ್ತು ದಾಖಲೆಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    'register.role.doctorDesc': 'ರೋಗಿಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    'register.button.continueAs': '{{role}} ಆಗಿ ಮುಂದುವರಿಸಿ',
    'register.button.back': 'ಹಿಂದೆ',
    'register.button.continue': 'ಮುಂದುವರಿಸಿ',
    'register.button.creating': 'ಖಾತೆ ರಚಿಸಲಾಗುತ್ತಿದೆ...',
    'register.button.create': 'ಖಾತೆ ರಚಿಸಿ',
    'register.card.personalInfo': 'ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ',
    'register.card.healthProfile': 'ಆರೋಗ್ಯ ಪ್ರೊಫೈಲ್',
    'register.card.professionalDetails': 'ವೃತ್ತಿಪರ ವಿವರಗಳು',
    'register.field.firstName': 'ಮೊದಲ ಹೆಸರು',
    'register.field.lastName': 'ಕೊನೆಯ ಹೆಸರು',
    'register.field.username': 'ಬಳಕೆದಾರ ಹೆಸರು',
    'register.field.email': 'ಇಮೇಲ್ ವಿಳಾಸ',
    'register.field.mobile': 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    'register.field.hospitalId': 'ಆಸ್ಪತ್ರೆ ಐಡಿ',
    'register.field.bloodType': 'ರಕ್ತ ಗುಂಪು',
    'register.field.allergies': 'ಅಲರ್ಜಿ',
    'register.field.specialisation': 'ವಿಶೇಷತೆ',
    'register.field.password': 'ಪಾಸ್ವರ್ಡ್',
    'register.field.confirmPassword': 'ಪಾಸ್ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
    'register.summary.title': 'ಖಾತೆ ಸಾರಾಂಶ',
    'register.summary.name': 'ಹೆಸರು',
    'register.summary.role': 'ಪಾತ್ರ',
    'register.login.prompt': 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?',
    'register.login.cta': 'ಸೈನ್ ಇನ್',

    'patient.alert.errorTitle': 'ದೋಷ',
    'patient.alert.markDoseFailed': 'ಡೋಸ್ ಗುರುತಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    'patient.greeting.morning': 'ಶುಭೋದಯ',
    'patient.greeting.afternoon': 'ಶುಭ ಮಧ್ಯಾಹ್ನ',
    'patient.greeting.evening': 'ಶುಭ ಸಂಜೆ',
    'patient.title': 'ನನ್ನ ಆರೋಗ್ಯ',
    'patient.banner.scheduledToday': 'ಔಷಧಿಗಳು ಇಂದು ನಿಗದಿಯಾಗಿದೆ',
    'patient.banner.viewSchedule': 'ಷೆಡ್ಯೂಲ್ ನೋಡಿ',
    'patient.banner.report': 'ವರದಿ',
    'patient.stats.medicines': 'ಔಷಧಿಗಳು',
    'patient.stats.adherence': 'ಅನುಸರಣೆ',
    'patient.stats.records7d': 'ದಾಖಲೆಗಳು (7 ದಿನ)',
    'patient.stats.alerts': 'ಅಲರ್ಟ್‌ಗಳು',
    'patient.section.todaysMeds': 'ಇಂದಿನ ಔಷಧಿಗಳು',
    'patient.section.weeklyAdherence': 'ವಾರದ ಅನುಸರಣೆ',
    'patient.section.recentReports': 'ಇತ್ತೀಚಿನ ವರದಿಗಳು',
    'patient.empty.noMedsToday': 'ಇಂದು ಔಷಧಿ ವೇಳಾಪಟ್ಟಿ ಇಲ್ಲ',
    'patient.empty.noReports': 'ಇನ್ನೂ ವರದಿಗಳು ಅಪ್ಲೋಡ್ ಆಗಿಲ್ಲ',
    'patient.score.healthScore': 'ಆರೋಗ್ಯ ಅಂಕೆ',
    'patient.score.excellent': 'ಉತ್ತಮ',
    'patient.score.good': 'ಚೆನ್ನಾಗಿದೆ',
    'patient.score.improving': 'ಸುಧಾರಿಸುತ್ತಿದೆ',
    'patient.score.dosesTaken': 'ತೆಗೆದುಕೊಂಡ ಡೋಸ್‌ಗಳು',
    'patient.score.pending': 'ಬಾಕಿ',
    'patient.weekly.onTrack': 'ಸರಿಯಾದ ದಾರಿಯಲ್ಲಿ',
    'patient.weekly.keepGoing': 'ಮುಂದುವರಿಸಿ',
    'patient.qa.symptoms': 'ಲಕ್ಷಣಗಳು',
    'patient.qa.reports': 'ವರದಿಗಳು',
    'patient.qa.medicines': 'ಔಷಧಿಗಳು',
    'patient.qa.qrProfile': 'QR ಪ್ರೊಫೈಲ್',

    'doctor.title': 'ಡಾಕ್ಟರ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'doctor.stats.totalPatients': 'ಒಟ್ಟು ರೋಗಿಗಳು',
    'doctor.stats.criticalAlerts': 'ಗಂಭೀರ ಅಲರ್ಟ್‌ಗಳು',
    'doctor.stats.moderateAlerts': 'ಮಧ್ಯಮ ಅಲರ್ಟ್‌ಗಳು',
    'doctor.stats.missed24h': 'ಮಿಸ್ ಆದವು (24ಗಂ)',
    'doctor.section.recentAlerts': 'ಇತ್ತೀಚಿನ ರೋಗಿ ಅಲರ್ಟ್‌ಗಳು',
    'doctor.section.patientsOverview': 'ರೋಗಿಗಳ ಅವಲೋಕನ',
    'doctor.empty.noRecentAlerts': 'ಇತ್ತೀಚಿನ ಅಲರ್ಟ್‌ಗಳು ಇಲ್ಲ',
    'doctor.empty.noPatients': 'ಇನ್ನೂ ರೋಗಿಗಳು ನಿಯೋಜಿಸಲ್ಪಟ್ಟಿಲ್ಲ',
    'doctor.empty.noPatientsHint': 'ನಿಯೋಜಿಸಿದ ನಂತರ ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ',
    'doctor.qa.patients': 'ರೋಗಿಗಳು',
    'doctor.qa.alerts': 'ಅಲರ್ಟ್‌ಗಳು',
    'doctor.qa.messages': 'ಸಂದೇಶಗಳು',
    'doctor.qa.notifications': 'ಅಧಿಸೂಚನೆಗಳು',
  },

  bh: {
    'common.patient': 'मरीज',
    'common.doctor': 'डॉक्टर',
    'common.cancel': 'रद्द करीं',
    'common.continue': 'आगे बढ़ीं',
    'common.language': 'भाषा',
    'common.user': 'यूजर',
    'common.loading': 'लोड होत बा...',
    'common.viewAll': 'सब देखीं',
    'common.view': 'देखीं',
    'common.add': '+ जोड़ीं',
    'common.retry': 'फेर कोशिश करीं',
    'common.error': 'गलती',
    'msg.title': 'संदेश',
    'msg.subtitle': 'मरीज बातचीत',
    'msg.noMessagesYet': 'अबही ले कवनो संदेश नइखे',
    'msg.searchPlaceholder': 'मरीज खोजीं...',
    'msg.chat': 'चैट',
    'msg.typeMessage': 'संदेश लिखीं...',
    'notif.title': 'सूचना',
    'notif.markAll': 'सब मार्क करीं',
    'notif.unread': 'अनरीड',
    'notif.allCaughtUp': 'सब अपडेट बा!',
    'notif.noneHere': 'इहाँ कवनो सूचना नइखे।',
    'notif.loading': 'सूचना लोड होत बा...',
    'notif.doctorTitle': 'डॉक्टर सूचना',
    'notif.patientTitle': 'मरीज सूचना',
    'notif.doctorSub': 'मरीज अलर्ट अउर सिस्टम अपडेट',
    'notif.patientSub': 'दवाई, संदेश अउर अपडेट',
    'notif.filter.all': 'सब',
    'notif.filter.unread': 'अनरीड',
    'notif.filter.critical': 'गंभीर',
    'notif.filter.report': 'रिपोर्ट',
    'notif.filter.medicine': 'दवाई',
    'notif.filter.message': 'संदेश',
    'notif.error.loadFailed': 'सूचना लोड ना भइल',
    'notif.error.markOne': 'रीड मार्क ना भइल',
    'notif.error.markAll': 'सब रीड मार्क ना भइल',
    'patients.title': 'मरीज',
    'patients.totalPatients': 'कुल मरीज',
    'patients.loading': 'मरीज लोड होत बा...',
    'patients.critical': 'गंभीर',
    'patients.monitor': 'निगरानी में',
    'patients.stable': 'स्थिर',
    'patients.searchPlaceholder': 'नाम, हालत से खोजीं...',
    'patients.showing': 'दिखावल जा रहल बा',
    'patients.of': 'में से',
    'patients.blood': 'ब्लड',
    'patients.allergies': 'एलर्जी',
    'patients.viewDetails': 'विवरण देखीं',
    'patients.noPatients': 'कवनो मरीज ना मिलल',
    'patients.tryAnotherSearch': 'दोसर खोज शब्द इस्तेमाल करीं',
    'alerts.title': 'अलर्ट',
    'alerts.subtitle': 'कार्रवाई जरूरी बा',
    'alerts.totalAlerts': 'कुल अलर्ट',
    'alerts.pending': 'लंबित',
    'alerts.responded': 'जवाब दिहल',
    'alerts.loading': 'अलर्ट लोड होत बा...',
    'alerts.pendingAction': 'लंबित अलर्ट - तुरंत कार्रवाई',
    'alerts.recommended': 'सुझाव',
    'alerts.viewPatient': 'मरीज देखीं',
    'alerts.sendSms': 'SMS भेजीं',
    'alerts.markResponded': 'जवाब दिहल मार्क करीं',
    'alerts.dismiss': 'हटाईं',
    'alerts.allCaughtUp': 'सब नियंत्रण में बा!',
    'alerts.noPending': 'अभी कवनो लंबित अलर्ट नइखे।',
    'alerts.sendSmsViaTwilio': 'Twilio से SMS भेजीं',
    'alerts.to': 'के',
    'alerts.message': 'संदेश',
    'alerts.typeMessage': 'अपना संदेश लिखीं...',
    'alerts.sendViaTwilio': 'Twilio से भेजीं',
    'alerts.smsSentTitle': 'SMS भेजाइल',
    'alerts.messageSentTo': 'संदेश भेजाइल',
    'alerts.viaTwilio': 'के Twilio से।',
    'alerts.loadFailed': 'अलर्ट लोड ना भइल',
    'alerts.unknown': 'अज्ञात',
    'med.title': 'दवाई',
    'med.subtitle': 'अपना दवाई ट्रैक करीं',
    'med.alert.requiredTitle': 'जरूरी',
    'med.alert.enterMedicineName': 'दवाई नाम डालीं',
    'med.alert.enterDosage': 'डोज़ डालीं',
    'med.alert.successTitle': 'सफल',
    'med.alert.added': 'दवाई सफलतापूर्वक जोड़ाइल',
    'med.alert.errorTitle': 'गलती',
    'med.error.fetchFailed': 'दवाई डेटा ना मिलल',
    'med.error.addFailed': 'दवाई जोड़ल ना जा सकल',
    'med.error.markDoseFailed': 'डोज़ मार्क ना भइल',
    'med.stats.active': 'सक्रिय दवाई',
    'med.stats.takenToday': 'आज लेहल',
    'med.stats.pending': 'बाकी',
    'med.stats.avgAdherence': 'औसत पालन',
    'med.section.todaySchedule': 'आज के शेड्यूल',
    'med.section.weeklyAdherence': 'साप्ताहिक पालन',
    'med.section.myMeds': 'हमार दवाई',
    'med.empty.noScheduled': 'कवनो दवाई शेड्यूल नइखे',
    'med.empty.noMeds': 'अभी ले दवाई जोड़ल नइखे',
    'med.badge.taken': 'लेहल',
    'med.action.take': 'लीं',
    'med.action.retake': 'फेर लीं',
    'med.action.addMedicine': 'दवाई जोड़ीं',
    'med.avg': 'औसत',
    'med.noSchedule': 'शेड्यूल नइखे',
    'med.started': 'शुरू',
    'med.modal.addNew': 'नया दवाई जोड़ीं',
    'med.field.name': 'दवाई नाम',
    'med.field.dosage': 'डोज़',
    'med.field.frequency': 'आवृत्ति',
    'med.field.timeSlots': 'समय स्लॉट',
    'med.field.instructions': 'निर्देश (वैकल्पिक)',
    'med.placeholder.name': 'जइसे: पैरासिटामोल',
    'med.placeholder.dosage': 'जइसे: 500mg',
    'med.placeholder.time': 'HH:MM',
    'med.placeholder.instructions': 'जइसे: खाना के बाद लीं',

    'login.brandSub': 'हेल्थ प्लेटफॉर्म',
    'login.title': 'फेर से स्वागत बा',
    'login.subtitle': 'अपना खाता में साइन इन करीं',
    'login.mode.email': 'ईमेल',
    'login.mode.mobile': 'मोबाइल',
    'login.mode.username': 'यूजरनेम',
    'login.mode.hospitalId': 'हॉस्पिटल आईडी',
    'login.field.email': 'ईमेल पता',
    'login.field.mobile': 'मोबाइल नंबर',
    'login.field.username': 'यूजरनेम',
    'login.field.hospitalId': 'हॉस्पिटल आईडी',
    'login.field.password': 'पासवर्ड',
    'login.placeholder.password': 'अपना पासवर्ड डालीं',
    'login.button.signingIn': 'साइन इन होत बा...',
    'login.button.signInAs': '{{role}} के रूप में साइन इन करीं',
    'login.error.enterPassword': 'कृपया पासवर्ड डालीं।',
    'login.error.enterEmail': 'कृपया ईमेल डालीं।',
    'login.error.enterMobile': 'कृपया मोबाइल नंबर डालीं।',
    'login.error.enterUsername': 'कृपया यूजरनेम डालीं।',
    'login.error.enterHospitalId': 'कृपया हॉस्पिटल आईडी डालीं।',
    'login.error.failedDefault': 'लॉगिन असफल भइल। फेर कोशिश करीं।',
    'login.error.failedTitle': 'लॉगिन असफल',
    'login.demo.quickAccess': 'जल्दी डेमो प्रवेश',
    'login.demo.modeTitle': 'डेमो मोड',
    'login.demo.modeBody': 'डेमो में ऑथेंटिकेशन स्किप हो जाला। पूरा फीचर खातिर खाता बनाईं या लॉगिन करीं।',
    'login.demo.continue': 'डेमो जारी रखीं',
    'login.register.prompt': 'खाता नइखे?',
    'login.register.cta': 'खाता बनाईं',

    'register.step.chooseRole': 'रोल चुनाईं',
    'register.step.personalInfo': 'व्यक्तिगत जानकारी',
    'register.step.healthProfile': 'हेल्थ प्रोफाइल',
    'register.header.subtitle': 'आजिए MediVault जॉइन करीं',
    'register.header.step': 'स्टेप',
    'register.alert.missingFieldsTitle': 'जानकारी अधूरा बा',
    'register.alert.missingFieldsBody': 'First Name, Last Name आ Email भरल जरूरी बा।',
    'register.alert.hospitalIdRequired': 'डॉक्टर रजिस्ट्रेशन खातिर Hospital ID जरूरी बा।',
    'register.alert.errorTitle': 'गलती',
    'register.alert.fillRequired': 'कृपया सब जरूरी जानकारी भरि दीं',
    'register.alert.passwordMismatch': 'पासवर्ड मिलत नइखे',
    'register.alert.passwordMin': 'पासवर्ड कम से कम 8 अक्षर के होखे के चाहीं',
    'register.alert.hospitalIdDoctor': 'डॉक्टर खातिर Hospital ID जरूरी बा',
    'register.role.patientDesc': 'हेल्थ आ रिकॉर्ड ट्रैक करीं',
    'register.role.doctorDesc': 'मरीज के मैनेज करीं',
    'register.button.continueAs': '{{role}} बनके आगे बढ़ीं',
    'register.button.back': 'पीछे',
    'register.button.continue': 'आगे बढ़ीं',
    'register.button.creating': 'खाता बनावल जा रहल बा...',
    'register.button.create': 'खाता बनाईं',
    'register.card.personalInfo': 'व्यक्तिगत जानकारी',
    'register.card.healthProfile': 'हेल्थ प्रोफाइल',
    'register.card.professionalDetails': 'पेशेवर जानकारी',
    'register.field.firstName': 'पहिला नाम',
    'register.field.lastName': 'आखिरी नाम',
    'register.field.username': 'यूजरनेम',
    'register.field.email': 'ईमेल पता',
    'register.field.mobile': 'मोबाइल नंबर',
    'register.field.hospitalId': 'हॉस्पिटल आईडी',
    'register.field.bloodType': 'ब्लड ग्रुप',
    'register.field.allergies': 'एलर्जी',
    'register.field.specialisation': 'विशेषज्ञता',
    'register.field.password': 'पासवर्ड',
    'register.field.confirmPassword': 'पासवर्ड दुबारा',
    'register.summary.title': 'खाता सारांश',
    'register.summary.name': 'नाम',
    'register.summary.role': 'रोल',
    'register.login.prompt': 'पहिले से खाता बा?',
    'register.login.cta': 'साइन इन',

    'patient.alert.errorTitle': 'गलती',
    'patient.alert.markDoseFailed': 'डोज़ मार्क ना भइल। फेर कोशिश करीं।',
    'patient.greeting.morning': 'सुप्रभात',
    'patient.greeting.afternoon': 'नमस्कार',
    'patient.greeting.evening': 'शुभ संध्या',
    'patient.title': 'हमार हेल्थ',
    'patient.banner.scheduledToday': 'दवाई आज निर्धारित बा',
    'patient.banner.viewSchedule': 'शेड्यूल देखीं',
    'patient.banner.report': 'रिपोर्ट',
    'patient.stats.medicines': 'दवाई',
    'patient.stats.adherence': 'पालन',
    'patient.stats.records7d': 'रिकॉर्ड (7 दिन)',
    'patient.stats.alerts': 'अलर्ट',
    'patient.section.todaysMeds': 'आज के दवाई',
    'patient.section.weeklyAdherence': 'साप्ताहिक पालन',
    'patient.section.recentReports': 'हाल के रिपोर्ट',
    'patient.empty.noMedsToday': 'आज खातिर दवाई शेड्यूल नइखे',
    'patient.empty.noReports': 'अभी ले कवनो रिपोर्ट अपलोड नइखे भइल',
    'patient.score.healthScore': 'हेल्थ स्कोर',
    'patient.score.excellent': 'बहुत बढ़िया',
    'patient.score.good': 'ठीक बा',
    'patient.score.improving': 'सुधार होत बा',
    'patient.score.dosesTaken': 'लेहल डोज़',
    'patient.score.pending': 'बाकी',
    'patient.weekly.onTrack': 'सही राह पर',
    'patient.weekly.keepGoing': 'जारी रखीं',
    'patient.qa.symptoms': 'लक्षण',
    'patient.qa.reports': 'रिपोर्ट',
    'patient.qa.medicines': 'दवाई',
    'patient.qa.qrProfile': 'QR प्रोफाइल',

    'doctor.title': 'डॉक्टर डैशबोर्ड',
    'doctor.stats.totalPatients': 'कुल मरीज',
    'doctor.stats.criticalAlerts': 'गंभीर अलर्ट',
    'doctor.stats.moderateAlerts': 'मध्यम अलर्ट',
    'doctor.stats.missed24h': 'मिस्ड (24 घंटा)',
    'doctor.section.recentAlerts': 'हाल के मरीज अलर्ट',
    'doctor.section.patientsOverview': 'मरीज अवलोकन',
    'doctor.empty.noRecentAlerts': 'हाल में कवनो अलर्ट नइखे',
    'doctor.empty.noPatients': 'अभी ले कवनो मरीज असाइन नइखे',
    'doctor.empty.noPatientsHint': 'असाइन होखे पर इहाँ दिखी',
    'doctor.qa.patients': 'मरीज',
    'doctor.qa.alerts': 'अलर्ट',
    'doctor.qa.messages': 'संदेश',
    'doctor.qa.notifications': 'सूचना',
  },
};

export const supportedLanguages: Array<{ code: LanguageCode; label: string }> = [
  { code: 'en', label: 'English' },
  { code: 'hi', label: 'Hindi' },
  { code: 'ta', label: 'Tamil' },
  { code: 'kn', label: 'Kannada' },
  { code: 'bh', label: 'Bhojpuri' },
];

type TranslateParams = Record<string, string>;

interface LanguageContextValue {
  language: LanguageCode;
  setLanguage: (next: LanguageCode) => Promise<void>;
  t: (key: string, params?: TranslateParams) => string;
}

const LanguageContext = createContext<LanguageContextValue>({
  language: 'en',
  setLanguage: async () => {},
  t: (key: string) => key,
});

function interpolate(template: string, params?: TranslateParams) {
  if (!params) return template;
  return template.replace(/\{\{(.*?)\}\}/g, (_, rawKey: string) => {
    const pKey = rawKey.trim();
    return params[pKey] ?? '';
  });
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>('en');

  useEffect(() => {
    const loadStoredLanguage = async () => {
      try {
        const saved = await AsyncStorage.getItem(STORAGE_KEY);
        if (saved && supportedLanguages.some((item) => item.code === saved)) {
          setLanguageState(saved as LanguageCode);
        }
      } catch (error) {
        console.error('Failed to load language:', error);
      }
    };

    loadStoredLanguage();
  }, []);

  const setLanguage = useCallback(async (next: LanguageCode) => {
    setLanguageState(next);
    try {
      await AsyncStorage.setItem(STORAGE_KEY, next);
    } catch (error) {
      console.error('Failed to save language:', error);
    }
  }, []);

  const t = useCallback((key: string, params?: TranslateParams) => {
    const current = resources[language][key];
    const fallback = resources.en[key] || key;
    return interpolate(current || fallback, params);
  }, [language]);

  const value = useMemo(() => ({ language, setLanguage, t }), [language, setLanguage, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
